//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISFINALPROJECT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDatabaseEntities1 : DbContext
    {
        public ProjectDatabaseEntities1()
            : base("name=ProjectDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentModule> StudentModule { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Assigments> Assigments { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<StudentAssignment> StudentAssignment { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    }
}
